### ISSUE TITLE
Ability to hide permission touch prompt icon

### ISSUE THREAD

**Issue by direx1** [thomasloven/hass-browser_mod#438] opened 2022-09-14 21:10 UTC
I would like the option to hide this or auto accept whatever the purpose is. It's losing WAF points lol

**Comment by FrnchFrgg** [comment] 2022-09-15 06:52
Duplicate of #400 I think

**Comment by MSandro** [comment] 2022-09-20 09:07
#400 describes how to hide the icon.
but I have no idea how to enable auto-accept. 
I am using Browser-Mod to Play Music on my Google Nest Hub without interupting the Dashboard Streaming.
but pressing the screen every time it re-connects is very annoying.

**Comment by Mincka** [comment] 2022-12-22 09:51
> I have no idea how to enable auto-accept. 
Indeed, its purpose is to request a **manual** interaction because it cannot be "auto-accepted" for privacy reason.
The issue is that it seems to be displayed even when there is no need. You will not get more from this issue that can be achieved in #400: an option to never show the icon.

**Closed** 2022-12-27 14:46 UTC
Labels: feature-request
