### ISSUE TITLE
Add back service lovelace_reload

### ISSUE THREAD

**Issue by clau-bucur** [thomasloven/hass-browser_mod#447] opened 2022-09-21 10:44 UTC
Would it be possible to add back the `lovelace_reload` service existing in v1?
I was using it to automatically reload my views after I had made a change to YAML files.

Thanks!

**Comment by FrnchFrgg** [comment] 2022-09-21 16:51
Duplicate of #424 
There is a `browser_mod.refresh` service doing the same thing AFAICT.

**Comment by clau-bucur** [comment] 2022-09-21 18:46
Thanks, haven't noticed that ticket even though I checked first for one.

**Closed** 2022-09-21 18:47 UTC
Labels: feature-request

**Comment by u8915055** [comment] 2022-10-11 16:43
I dont think the browser_mod.refresh does the same thing.  I am trying it now, and used lovelace_reload extensively.  It seems refresh just refreshes the current page.  When i used lovelace_reload, i could call the service from one browser window on my mac and my front end on my phone would update!  The reason this was so useful is that any changes in things like button_card templates need that reload to show the changes, without reloading home assistant.  At least i cannot find another way.. perhaps clearing the browser cache might do it but that's such a pain.  Please add that service back.

**Comment by u8915055** [comment] 2022-10-11 17:19
Ok i might be getting somewhere.  i did not know that you had to go into browser_mod settings and register the current browser.. ie 'Enable this browser as a Device in Home Assistant'.  Once i did this it seems to be working (lovelace_reload).  It was so automatic in the previous version but if this is what has to be done to make this work, then great.  I just have to make sure i enable this on all devices in the home that open up home assistant.
