### ISSUE TITLE
[FR] Force Enable for Specified User or Global HA Enforcement

### ISSUE THREAD

**Issue by LordNex** [thomasloven/hass-browser_mod#477] opened 2022-10-23 18:34 UTC
I would like the ability to force the browser mod on for any device a specific user logs into Home Assistant from. Or a global enforcement of all users in HA have it enabled by default or mandatorily. This would help with having just one Kiosk user account and then forcing those to logon to certain wall panels via a Lovelace cast.

**Comment by jatgm1** [comment] 2022-11-11 14:27
I second this. I thought this was already a thing on the original version actually.

**Comment by jatgm1** [comment] 2022-11-25 19:33
Hey, just wondering, is this something that might be doable? I actually have my home assistant set up perfectly but the one issue is whether or not someone's browser is registered and none of the users are really capable of figuring it out. Also this makes it harder to see if their login details could have been leaked because there's no way to see if any other devices have been added from a specific account. Also if their was an entity created that was simply the number of devices registered (including automatically), and am entity with the number of devices registered per user account, I can set a trigger that goes off if someone logs in that has not logged in before, in general, and then specifically from each account, to be notified if someone logs in and which account was used. To change the password.

**Comment by LordNex** [comment] 2022-12-02 10:07
I agree. The ability this tool provides has lots of potential. Having a more “Administrative View” of connected devices and the ability to control them would really put this over the top. Personally I use it to be able to stream music from Music Assistant, back to my phone and then to my trucks bluetooth. It's the only way I've been able to listen to my music library remotely

**Comment by thomasloven** [comment] 2022-12-29 21:38
Duplicate of #414

**Closed by thomasloven** 2022-12-29 21:38 UTC
Labels: feature-request
