### ISSUE TITLE
Report: 0.117.0b1 (beta) of Home Assistant the custom component does not work

### ISSUE THREAD

**Issue by RssFra97** [thomasloven/hass-browser_mod#151] opened 2020-10-22 14:42 UTC
I wanted to point out that in the Home Assistant 0.117 beta the component does not work, maybe it is a bug of a new change to the interface

**Comment by KTibow** [comment] 2020-10-22 17:44
Hey! Mind helping debug? Share your HA logs, with the filter level set to INFO.

**Comment by djmalin** [comment] 2020-10-22 22:29
i heve the same problem

2020-10-23 00:25:20 ERROR (MainThread) [frontend.js.latest.202010211] https://192.1x.x.x:8123/browser_mod.js:149:6221 Uncaught TypeError: Cannot read property 'style' of undefined

**Comment by mynameisdaniel32** [comment] 2020-10-22 22:49
Same here, popup actions don't work and logs are flooded with the error message djmalin posted, with a few of these mixed in:
`Uncaught TypeError: Cannot read property 'playedOnce' of undefined`

Tried clearing the cache, running 0.117.0b1 and Browser Mod 1.1.7. Seems to happen in all browsers/devices.

**Comment by RssFra97** [comment] 2020-10-22 23:03
> Hey! Mind helping debug? Share your HA logs, with the filter level set to INFO.

as soon as I wake up I do

**Comment by RssFra97** [comment] 2020-10-23 08:50
When I press a button to open the popup this error comes out:
2020-10-23 10:48:31 ERROR (MainThread) [frontend.js.latest.202010211] https://subd.dominio.net/browser_mod.js:149:6221 Uncaught TypeError: Cannot read property 'style' of undefined

**Comment by KTibow** [comment] 2020-10-23 13:42
Alright, alright, I know that I said share your HA logs, but now it'd be good if you share your browser console logs. It's a frontend error.

**Comment by RssFra97** [comment] 2020-10-23 14:42
> Alright, alright, I know that I said share your HA logs, but now it'd be good if you share your browser console logs. It's a frontend error.

ok
Uncaught TypeError: Cannot read property 'style' of undefined
    at b.no_blackout (browser_mod.js:149)
no_blackout @ browser_mod.js:149

**Comment by KTibow** [comment] 2020-10-23 17:31
@thomasloven have you looked at this issue? Do you know what this is caused by or how to fix?

**Comment by thomasloven** [comment] 2020-10-23 19:59
Yeah. It's a very weird timing issue that's fixed on the branch I've been working on during the day.
Unfortunately, I've been changing too many things at once, so I can't push the update until I do a lot more testing to make sure I didn't break anything...

**Comment by KTibow** [comment] 2020-10-23 20:28
I'm just getting this:
![image](https://user-images.githubusercontent.com/10727862/97051158-8d1dfc00-1533-11eb-8a94-530882ce265f.png)

**Comment by thomasloven** [comment] 2020-10-23 20:32
The problem is that one of those https://github.com/thomasloven/hass-browser_mod/blob/master/js/main.js#L84-L87 get triggered before this happens https://github.com/thomasloven/hass-browser_mod/blob/master/js/main.js#L108 because that https://github.com/thomasloven/hass-browser_mod/blob/master/js/main.js#L88 sometimes takes a while.
A very simple fix, really. Just move this to before that and those.

(Or keep your mouse perfectly still until the interface has loaded completely and you should be fine.)

**Comment by RssFra97** [comment] 2020-10-23 20:34
> The problem is that one of those https://github.com/thomasloven/hass-browser_mod/blob/master/js/main.js#L84-L87 get triggered before this happens https://github.com/thomasloven/hass-browser_mod/blob/master/js/main.js#L108 because that https://github.com/thomasloven/hass-browser_mod/blob/master/js/main.js#L88 sometimes takes a while.
> A very simple fix, really. Just move this to before that and those. But again, I can't really make that fix right now.
> 
> (Or keep your mouse perfectly still until the interface has loaded completely and you should be fine.)

👍👍👍👍👍

**Comment by thomasloven** [comment] 2020-10-23 22:33
Ok. I´ve just pushed the huge restructure.
A lot have changed, but hopefully very little that anyone should notice.

I'm not ready to make a full release yet, though, because I haven't tested it in FKB.

If you want to try version 1.2.0 prerelease, you can choose to install `master` from HACS.

**Comment by Mariusthvdb** [comment] 2020-10-24 21:07
well, not sure if that helped:
```
2020-10-24 23:03:07 ERROR (MainThread) [homeassistant.setup] Error during setup of component browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/browser_mod/__init__.py", line 50, in async_setup
    device.trigger_update()
AttributeError: 'BrowserModConnection' object has no attribute 'trigger_update'
2020-10-24 23:03:08 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform browser_mod.media_player: Unable to set up component.
2020-10-24 23:03:09 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform browser_mod.sensor: Unable to set up component.
2020-10-24 23:03:09 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform browser_mod.binary_sensor: Unable to set up component.
2020-10-24 23:03:09 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform browser_mod.light: Unable to set up component.
2020-10-24 23:03:09 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform browser_mod.camera: Unable to set up component.
```

:-)
going back to the release version seems best for now, let me know if we can do anything to help.

**Comment by thomasloven** [comment] 2020-10-24 21:22
Ok. Tested in FKB, macOS app and iOS Safari.
Release 1.2.0 should fix this issue.

@Mariusthvdb Please open a new issue for problems which have no similarities to the one discussed.

**Closed by thomasloven** 2020-10-24 21:22 UTC

**Comment by Mariusthvdb** [comment] 2020-10-24 21:49
> @Mariusthvdb Please open a new issue for problems which have no similarities to the one discussed.
Sorry for that, posted because I had manually updated to the prerelease version mentioned above.

Now that I have updated to the release 1.2.0, all errors seem to have gone.
so thanks, and again apologies.

**Comment by thomasloven** [comment] 2020-10-25 17:36
Glad to hear!

**Comment by RssFra97** [comment] 2020-10-25 17:37
> Glad to hear!

thanks for the work
