### ISSUE TITLE
Popups no longer work in 0.106

### ISSUE THREAD

**Issue by vandalon** [thomasloven/hass-browser_mod#63] opened 2020-02-27 11:47 UTC
After updating to HA core 0.106, popups no longer work and i'm getting this error in the logs:

```
browser_mod.js:56:274 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
```

**Comment by ThePicklenat0r** [comment] 2020-02-27 13:19
I'm having the same issue, and am getting a similar error:

```
Logger: frontend.js.latest.202002204
First occured: February 26, 2020, 9:34:08 PM (20 occurences)
Last logged: 8:16:24 AM

https://[redacted]/browser_mod.js:56:314 Uncaught TypeError: Cannot assign to read only property 'deviceID' of object '#<Object>'
```

**Comment by ercsey** [comment] 2020-02-28 08:00
Same for me.

```http://ha-address/browser_mod.js:56:274 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'```

**Comment by vandalon** [comment] 2020-02-28 09:24
In 0.106.1 the error changed to:

`

2020-02-28 10:20:57 ERROR (MainThread) [frontend.js.latest.202002204] https://hass.net.wiebel.nl:8123/browser_mod.js:60:12066 TypeError: Attempted to assign to readonly property.

`

**Comment by jazzyisj** [comment] 2020-02-29 06:10
Same issue here but would like to note that global popups defined with popup_cards: in ui-lovelace.yaml are still working without error.

**Comment by deluxestyle** [comment] 2020-02-29 18:06
I'm having the same issue after update to 0.106.2
 If I call the browser_mod.popup with the button entity row it works. If call browser_mod.popup with the normal tap_action I get the error

**Comment by Dielee** [comment] 2020-03-01 08:50
Hello guys, I have the same error but there is a workaround for me. 
Configure your popup_cards:

```
views:
  - title: Home
    id: Home
    icon: mdi:home
    popup_cards:
      input_boolean.wecker: &wecker
        title: Wecker
        card:
          type: entities
          entities:
            - input_boolean.wecker
            - entity: input_datetime.wecker
              name: Weckzeit
            - entity: input_boolean.wecker_wochenende
              name: Wochenende
            - entity: input_boolean.schlafzimmer_rollo
              icon: mdi:window-open

```

and then leave the tap_action, like this:

```
        - type: glance
          title: Status
          columns: 5
          entities:
              - entity: sensor.waschmaschine_state
                name: Wäsche
              - entity: input_boolean.putzen
                tap_action:
                  action: toggle
              - entity: input_boolean.urlaub
                tap_action:
                  action: toggle
              - entity: input_boolean.wecker

```

Works for me, hope this helps..

**Comment by deluxestyle** [comment] 2020-03-01 09:19
I‘m using the same workaround with popular cards. Maybe it is not even a workaround. It works very well

**Comment by jazzyisj** [comment] 2020-03-02 17:26
With some fooling around I have discovered that disabling the deviceID tag allows all popups to work.  Obviously they will open on all devices but all is better than none!

**Comment by esbenlydiksen** [comment] 2020-03-03 19:50
I have the same problem. Removing the deviceID does not seem to make a difference. Keeping my fingers crossed for a fix.

**Comment by VDRainer** [comment] 2020-03-04 20:06
Thanks so much!
Can confirm, this works for me too and fixes https://github.com/thomasloven/hass-browser_mod/issues/61.

**Comment by pejotigrek** [comment] 2020-03-04 23:59
I have the same problem. from 0.106 to 0.106.5 still getting:

`2020-03-05 00:53:57 ERROR (MainThread) [frontend.js.latest.202002205] https://skyn3t.duckdns.org:27/browser_mod.js:60:314 Uncaught TypeError: Cannot assign to read only property 'deviceID' of object '#<Object>'`

tried this fix: https://github.com/thomasloven/hass-browser_mod/issues/63#issuecomment-594790445, unfortunately it doesn't work in my scenario.

popups started to work fine after removing all `deviceID` references from yaml.

I guess some proper fix is needed in the original code?

**Comment by jsiemek** [comment] 2020-03-05 00:19
I also can confirm that @CAB426  fix works for me.

**Comment by CAB426** [comment] 2020-03-05 17:28
@pejotigrek Can you post your card and popup config?  I'll take a look at it.

**Comment by pejotigrek** [comment] 2020-03-05 17:42
@CAB426 I've got plenty of them, but I guess that doesn't matter - so here's one of them: popup with informations about person's whereabouts opened after tapping on a person [words all in caps are redacted]:

```
  - entity: person.SOME_PERSON
    tap_action:
      action: call-service
      entity: person.SOME_PERSON
      service: browser_mod.popup
      service_data:
        deviceID: this
        title: "PERSON"
        card:
          type: vertical-stack
          cards:
          - type: markdown
            content: |
              ## PERSON is **{% if (states('person.SOME_PERSON') == 'home') %}w domu{% elif (states('person.SOME_PERSON') == 'not_home') %}poza domem{% else %}{{ states('person.SOME_PERSON') }}{% endif %}.**
              **Adres w pobliżu:**
              {{ state_attr('device_tracker.GOOGLE_MAPS', 'address') }}
              (z dokładnością do {{ state_attr('device_tracker.GOOGLE_MAPS', 'gps_accuracy') }}m)
              
              **Stan baterii:** {% if (state_attr('device_tracker.GOOGLE_MAPS', 'battery_charging') == false) %}{{ state_attr('device_tracker.GOOGLE_MAPS', 'battery_level') }}%{% else %}ładowanie{% endif %}
          - type: map
            entities:
            - person.SOME_PERSON
            default_zoom: 14
            dark_mode: false
```

that started to work after I commented out the `deviceID` line.

**Comment by CAB426** [comment] 2020-03-05 18:16
@pejotigrek What type of card is that?  The type isn't defined in the YAML provided.  I tried it as type: button and type: 'custom:button-card', and was not able to reproduce your issue.

Can you post a copy of your updated browser_mod.js?

**Comment by pejotigrek** [comment] 2020-03-05 18:35
@CAB426 oops! sorry, I've cut too fast - my [comment](https://github.com/thomasloven/hass-browser_mod/issues/63#issuecomment-595357317) is edited, I've pasted the rest of the code. it's a glance card.

also - browser_mod.js files in the attachement. original & edited by me [extension changed due to github filetype support].

[browser_mod_EDITED.js.txt](https://github.com/thomasloven/hass-browser_mod/files/4294485/browser_mod_EDITED.js.txt)
[browser_mod_ORIGINAL.js.txt](https://github.com/thomasloven/hass-browser_mod/files/4294487/browser_mod_ORIGINAL.js.txt)

**Comment by CAB426** [comment] 2020-03-05 19:02
@pejotigrek Everything looks good in your edited file.  I replaced my JS with your edited version and it works.  I added in a second entity to see if that had any impact and it did not. 

Have you cleared your cache?  Tried a different browser? Just wondering if something old is hanging around.

**Comment by pejotigrek** [comment] 2020-03-05 21:18
@CAB426 yep. cache cleared, dashboard page force-reloaded. even on a few devices [pc & mobile]. with no effect.

in most cases I use only one device a time, so popping up windows on every instance isn't that annoying, and removing `deviceID` isn't such a pain, but still it's strange that it behaves like this.

**Comment by vietlehung** [comment] 2020-03-10 03:55
@CAB426 thanks. it works in my case.

**Comment by thomasloven** [comment] 2020-03-31 13:16
Hey everyone. Could you please try release 25, and see if that fixes this?
When properly installed, your browser console should say "BROWSER_MOD 1.0.2 IS INSTALLED".

**Comment by ThePicklenat0r** [comment] 2020-03-31 20:52
Working for me as well on 0.107.7

**Comment by jazzyisj** [comment] 2020-04-01 01:08
107.7 Chrome, Firefox, Android all working perfectly.  Tack så mycket!

**Comment by thomasloven** [comment] 2020-04-01 07:20
Thanks! There were at least three different things all working together to make this not work, so I'll keep this issue open a while longer before calling it done.

Keep telling me if it works or not.

**Comment by pejotigrek** [comment] 2020-04-01 13:06
can confirm. working good! I could bring back `device: this` setting :)

**Comment by ronaldheft** [comment] 2020-04-01 13:26
Working well here on Mobile Safari and Safari. Thanks!

**Comment by drletai** [comment] 2020-04-05 19:50
Strange behaviour here: after flushing the cache works it perfect again, till I set a specific dashboard as default. With that I get the red error again... So there is a problem with multiple dashboards. I think I need to switch back.

**Comment by drletai** [comment] 2020-04-05 20:29
I have switched back to one single dashboard, now I have lost everything, it works just once after flushing the cache...

**Closed** 2020-10-21 18:59 UTC
