### ISSUE TITLE
Getting interaction required symbol even if not using media_player or camera components

### ISSUE THREAD

**Issue by LeoCal** [thomasloven/hass-browser_mod#462] opened 2022-10-03 15:58 UTC
My Home Assistant version: 2022.9.7

**What I am doing:**
Browser_mod is configured in my home assistant instance simply to customize the more-info dialog of a few entities.
I'm not using the media_player or camera components of browser_mod.
According to the Browser Mod Settings page, the interaction requirement (clicking on the screen from time to time) is needed for privacy reasons from many browsers before allowing audio playback or video capture. However, I don't need any of the two, so I was assuming I would not get that annoying required interaction prompt, while it seems to be the case.
If that's not possible today, may I ask to add this functionality going forward? The idea would be to provide a toggle to let a user decide whether to include the media_player or camera components. If they are not required by the user, the required interaction prompts should not be shown.

**What I expected to happen:**
 I was expecting not to get the annoying required interaction prompt, if not interested in using the media_player or camera components of browser_mod.

**What happened instead:**
Getting the required interaction prompt from time to time.

**Minimal** steps to reproduce:
Install browser_mod and use it for some time (go through HA restarts, etc.)

```yaml
N/A
```

**Error messages from the browser console:**

```
N/A
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Vendo232** [comment] 2022-10-31 17:19
any update on this? Any way to turn it off?

**Comment by thomasloven** [comment] 2022-12-29 22:03
Duplicate of #400

**Closed by thomasloven** 2022-12-29 22:03 UTC

**Comment by Vendo232** [comment] 2022-12-29 22:57
What is the fix for this to prevent corrupting layout in lovelace? Every 2-3 days I have to restart my tablet HA because of this useless icon.
