### ISSUE TITLE
Bring back URL-based setting of browserID (deviceID)

### ISSUE THREAD

**Issue by OverZealous** [thomasloven/hass-browser_mod#524] opened 2023-01-24 17:40 UTC
I understand that it's hard to force the `browserID` to stick, which is fine. The previous version of browser mod supported adding `?deviceID=whatever` to the URL, and this pretty much eliminated the issue for me. If the browser ID changed, a simple refresh (in WallPanel) or clicking my bookmark (in a browser) instantly fixed the issue.

It really helps with wall-mounted tablets or other devices, since those often depend highly on being accurately labeled. For my WallPanel devices, I can trigger a reload using a REST command to all of my tablets, which then effectively reloads the page and resets the ID at that moment.

Hopefully I didn't miss anything, but I couldn't see anything about this in the docs or even in the codebase last time I checked.

**Comment by thomasloven** [comment] 2023-07-14 22:30
Will be in next release.

**Closed by thomasloven** 2023-07-14 22:30 UTC
Labels: feature-request

**Comment by thomasloven** [comment] 2023-07-14 22:34
Also duplicate of #496
