### ISSUE TITLE
After page refresh hide sidebar stop working

### ISSUE THREAD

**Issue by aLAN-LDZ** [thomasloven/hass-browser_mod#614] opened 2023-07-20 05:47 UTC
My Home Assistant version: last

I have android tablet with fully kiosk browser. On browser mod settings i set hide sidebar

After home page refresh sidebar is unhide

When i go to browser mod and click hide second time is hide to next page refresh

The problem is like this:

https://github.com/thomasloven/hass-browser_mod/issues/589

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment] 2023-07-22 10:26
Duplicate of #589

**Closed by thomasloven** 2023-07-22 10:26 UTC
