### ISSUE TITLE
Popup card global for dashboard

### ISSUE THREAD

**Issue by indykoning** [thomasloven/hass-browser_mod#411] opened 2022-09-07 18:16 UTC
In browser mod 1.x you defined your popups globally and these worked on every view within that dashboard.

On 2.x i have not been able to get this same behaviour running.
The reason i want this is because i had an entity (a weather chip) in my header with "header_cards" but i also have a larger weather card in a view.
Both of these would open the same popup, however now if i leave the view where the popup is on the popup in the header ceases to function (understandably so)

Also even though the popup cards get hidden they still impact the layout, i don't doubt you'd be able to do much about that though, i'll store them in a horizontal/vertical cart with one of the respective entities.

The visual editor for popups is absolutely great!

**Comment by indykoning** [comment] 2022-09-07 18:34
Update: i got the popups i need working on all views working by adding them as a header_card in my case as these are rendered on every view

There may be an other and better solution for this not requiring another integration, however this solves the issue for me.

**Comment by thomasloven** [comment] 2022-09-07 18:38
Duplicate of #361

**Closed by thomasloven** 2022-09-07 18:38 UTC
Labels: feature-request
