### ISSUE TITLE
Add the abbilty to define popup-card for whole dasboard.

### ISSUE THREAD

**Issue by TKpizza** [thomasloven/hass-browser_mod#430] opened 2022-09-12 13:51 UTC
i would love to make a popup dashboard that works within all pages of that dashboard. so that i can have one central location for every page

**Comment by GitHubGoody** [comment] 2022-11-24 12:34
Do subviews accomplish what you're after?

**Comment by thomasloven** [comment] 2022-12-29 22:38
Duplicate of #361

**Closed by thomasloven** 2022-12-29 22:38 UTC
Labels: feature-request
