### ISSUE TITLE
Blackout exceptions

### ISSUE THREAD

**Issue by KTibow** [thomasloven/hass-browser_mod#152] opened 2020-10-22 21:04 UTC
My browser console's being flooded with errors:
```js
Uncaught TypeError: this._blackout is undefined
    no_blackout https://ourliltreehouse.duckdns.org/browser_mod.js:149
browser_mod.js:149:6185
    no_blackout https://ourliltreehouse.duckdns.org/browser_mod.js:149
    no_blackout self-hosted:1161
```
![image](https://user-images.githubusercontent.com/10727862/96929708-6a2a1400-146f-11eb-9bd0-00888b2cb41b.png)
Sorry for low detail.

**Comment by thomasloven** [comment] 2020-10-23 22:23
Duplicate of #151. Not easy to tell from the start, though.

**Closed by thomasloven** 2020-10-23 22:23 UTC
