### ISSUE TITLE
Global setting and browser settings not showing up

### ISSUE THREAD

**Issue by rddelacosta** [thomasloven/hass-browser_mod#724] opened 2024-07-11 00:26 UTC
My Home Assistant version: 2024.7.1 / 2024.06.2

**What I am doing:**
Trying to change sideboard order

**What I expected to happen:**
Global settings to show up along with other browsers

**What happened instead:**
Nothing showing up

**Minimal** steps to reproduce:
just followed instructions but not working

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

<img width="512" alt="screengrab" src="https://github.com/thomasloven/hass-browser_mod/assets/159463203/cc6dd288-8a69-4afe-86b8-bb28627dd10b">

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by cbamesberger** [comment] 2024-07-11 15:29
I have the same issue

**Comment by JRDevo** [comment] 2024-07-12 08:24
Duplicate of #718?

**Closed** 2024-07-12 10:07 UTC
