### ISSUE TITLE
Android Companion App - Browser mod entites 'unavailable' after 5 minutes

### ISSUE THREAD

**Issue by tomjmul** [thomasloven/hass-browser_mod#500] opened 2022-12-12 11:26 UTC
My Home Assistant version: 0.XX.X

**What I am doing:**

Installed Browser Mod 2 on 2 android tablets, both using the HA Assistant Companion App. Registered both browsers and confirmed they can both connect.

**What I expected to happen:**

Able to control both browsers indefinitely by calling the various backend services

**What happened instead:**

Service calls work for 5 minutes, then the various entities become unavailable.

The browsers on 2 Samsung Galaxy tablets running the companion app become unavailable after 5 minutes. I've tried clearing cache data and keeing the connections open after 5 minutes, but nothing seems to work. The screen is also set to always on, so it's not a sleep issue.

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by mfabiani53** [comment] 2022-12-13 13:03
How you installed this integration from HA android companion app?
I did the same but when i click on browser_mod in the sidebar of the app i always get a blank screen, so i am not able to register the app as browser_mod device and, susseguently, not able to use the services only on the companion app.
For example if i have a script that opens a popup witht the browser_mod.popup service, it opens only on registered devices and not on the dashboard of the companion app.

**Comment by thomasloven** [comment] 2022-12-29 23:07
Duplicate of #452
Duplicate of #479
Duplicate of #492

**Closed by thomasloven** 2022-12-29 23:07 UTC
