### ISSUE TITLE
Side Panel Configuration not appearing for Non-Administrator Users

### ISSUE THREAD

**Issue by curt7000** [thomasloven/hass-browser_mod#368] opened 2022-09-03 22:42 UTC
Hi,

After updating to Ver. 2.0, I see that configuration is available via the Side Panel.  This is really great!  Only those browsers I want to control will be added, instead of getting dozens of dead entities over time!  Thank you!

However, I've noticed that my wall panel, setup with a non-administrator user, does not have access to the Browser Mod Side Panel icon, the icon does not appear.  Not sure if this is a bug or if I need to do something to the user to get this to show up.  I tried editing the user without luck.  I don't see a way to add a non-administrator user/browser.

**Comment by meichthys** [comment] 2022-09-04 00:37
I think this may be by design. A non-admin user with access to the browser-mod panel could remove other administrative user devices. To register the device, you should be able to add the user as admin, register the device, and then remove admin from the user. Not ideal, but it should be a one time configuration.

**Comment by curt7000** [comment] 2022-09-04 00:44
I think you are right.  I will give it a go.

Perhaps then a feature request to allow one to add non-admin browsers?

**Comment by ercsey** [comment] 2022-09-04 14:02
@meichthys  I did the same as you described but after removing users from the admin group their browser-mod device were also removed from the device list.

**Comment by meichthys** [comment] 2022-09-04 14:14
Hmm I guess this would be a bug then. I was making an optimistic assumption.

**Comment by thomasloven** [comment] 2022-09-04 22:09
Should be fixed now.

**Closed by thomasloven** 2022-09-04 22:09 UTC

**Comment by curt7000** [comment] 2022-09-04 23:54
This is great!  Thank you!
