### ISSUE TITLE
Registered Devices not showing on service tools

### ISSUE THREAD

**Issue by alexandrechoske** [thomasloven/hass-browser_mod#560] opened 2023-03-30 12:42 UTC
My Home Assistant version: 2023.02

**What I am doing:**
Trying to test services from Service Tool but no devices appears.

**What I expected to happen:**
Show the registered devices so I can trigger services

**What happened instead:**
Devices not showing on dropdown list

**Minimal** steps to reproduce:

I Have an automation running that I built with previous Browser Mod versions that is working fine, I used to have the device_id from the service tools so I can trigger another things.

```- id: '1676741822796'
  alias: Geral Casa - Dark/Light Mobile
  description: Mudar tema para claro ou escuro
  trigger:
  - platform: state
    entity_id: input_boolean.change_theme
    to:
    - 'on'
    - 'off'
  condition: []
  action:
  - service: browser_mod.set_theme
    target:
      device_id: de4bf60eb27fa46a24e57ea4228bcd0c
    data:
      dark: "{% if states('input_boolean.change_theme') == 'on' %}\n   dark \n{% else
        %}\n   light \n{% endif %}"
```

**Error messages from the browser console:**

![image](https://user-images.githubusercontent.com/47279355/228838722-7a0ff6ef-93a4-4421-bb0e-1bd84e2d6f0f.png)
![image](https://user-images.githubusercontent.com/47279355/228838775-363f8bfe-a265-4dc6-9ae9-ec294980be0c.png)
![image](https://user-images.githubusercontent.com/47279355/228838845-1783225a-389b-4c44-8083-865deb855332.png)

```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by justindekeizer** [comment] 2023-04-10 06:40
I have the same issue since 2023.4

**Comment by alexisspencer** [comment] 2023-04-25 05:04
me too

**Comment by nima-1102** [comment] 2023-05-07 20:03
Same here:

`Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest`

Browser Mod: v2.2.1

**Comment by thomasloven** [comment] 2023-07-14 23:05
Duplicate of #554

**Closed by thomasloven** 2023-07-14 23:05 UTC
