### ISSUE TITLE
Remote HA Dashboard (wall tablet) not reachable after HA restart

### ISSUE THREAD

**Issue by mmatesic01** [thomasloven/hass-browser_mod#427] opened 2022-09-12 08:48 UTC
My Home Assistant version: 2022.9.2

**What I am doing:**
Each time I restart HA, my remote dashboard on my wall tablet, which I have activated in browser mod, becomes unavailable.
I am running HA companion on my tablet. Clearing cache did not help.
I did not have such issues with browser mod 1.53.

**What I expected to happen:**
I would expect when HA restarts the dashboard on my tablet automatically registers that it is available.

**What happened instead:**
I have to restart HA companion on my remote wall tablet in order for it to be available again.

**Minimal** steps to reproduce:**
Restart HA

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [  ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [  ] Have made sure I am using the latest version of the plugin.

- [  ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [  ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by chinezbrun** [comment] 2022-11-21 17:53
really annoying the issue the same with https://github.com/thomasloven/hass-browser_mod/issues/405. i'm planning to roll back

**Comment by thomasloven** [comment] 2022-12-29 22:36
Duplicate of #405

**Closed by thomasloven** 2022-12-29 22:36 UTC
