### ISSUE TITLE
Detected that custom integration 'browser_mod' accesses hass.components.frontend

### ISSUE THREAD

**Issue by holdestmade** [thomasloven/hass-browser_mod#690] opened 2024-03-04 16:21 UTC
My Home Assistant version: 2024.3.0b5

**Error messages from the browser console:**

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156
First occurred: 4:14:27 pm (1 occurrences)
Last logged: 4:14:27 pm

Detected that custom integration 'browser_mod' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/browser_mod/mod_view.py, line 24: hass.components.frontend.async_register_built_in_panel(, please report it to the author of the 'browser_mod' custom integration
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by pejotigrek** [comment] 2024-03-07 00:21
I can confirm that in stable 2024.3.0 the problem is also visible in log:

```
2024-03-07 00:42:30.798 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/browser_mod/mod_view.py, line 24: hass.components.frontend.async_register_built_in_panel(, please report it to the author of the 'browser_mod' custom integration
```

**Comment by DaN66O** [comment] 2024-03-07 11:12
I also confirm this

**Comment by RalfLuig** [comment] 2024-03-08 21:26
I see the same Problem

**Comment by Destroyer061090** [comment] 2024-03-18 23:13
same warning

**Comment by IntExCZ** [comment] 2024-05-04 18:51
Fixed by pull request: https://github.com/thomasloven/hass-browser_mod/pull/705

**Comment by foxsam21** [comment] 2024-05-13 16:29
does that also fix this (hass.helpers.storage) warning?
```
Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
```

**Comment by IntExCZ** [comment] 2024-05-13 23:44
> does that also fix this (hass.helpers.storage) warning?
> 
> ```
> Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
> ```

How can be this warning message reproduced?
What is the version of HA?

**Comment by foxsam21** [comment] 2024-05-14 02:55
> > ```
> > Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
> > ```
> 
> How can be this warning message reproduced? What is the version of HA?

2024.5.2
not sure on how to reproduce, I don't know what is causing it. for me its in the logs whenever i restart HA.

**Comment by IntExCZ** [comment] 2024-05-14 08:06
@foxsam21
I am, for fail-safe reasons, one major version back (2024.4.4) so when I upgrade to 2024.5.2+ (when the 2024.6.0 releases), I will try to fix that ASAP.

**Comment by IntExCZ** [comment] 2024-06-07 01:03
> does that also fix this (hass.helpers.storage) warning?
> 
> ```
> Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
> ```

Fixed by pull request: https://github.com/thomasloven/hass-browser_mod/pull/710

**Comment by IntExCZ** [comment] 2024-06-07 19:53
`Entity None (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152463>, please report it to the author of the 'browser_mod' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

Fixed by pull request: https://github.com/thomasloven/hass-browser_mod/pull/711

**Closed** 2024-10-25 15:43 UTC
