### ISSUE TITLE
Migration handler not found for entry Browser Mod for browser_mod

### ISSUE THREAD

**Issue by saucedge** [thomasloven/hass-browser_mod#370] opened 2022-09-04 06:19 UTC
I'm getting the following error after updating to 2.0.1:

`2022-09-03 22:58:50.280 INFO (MainThread) [homeassistant.setup] Setting up browser_mod
2022-09-03 22:58:50.989 INFO (MainThread) [homeassistant.setup] Setup of domain browser_mod took 0.7 seconds
2022-09-03 22:58:51.029 ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry Browser Mod for browser_mod`

Any ideas?

**Comment by Symbiot78** [comment] 2022-09-04 06:24
same here.

**Comment by ElRubio17** [comment] 2022-09-04 07:03
Go to setting>integrations. Remove browser_mod inetgration and reinstall. It worked for me

**Comment by oyvindhauge** [comment] 2022-09-04 07:44
I was a dumbass and did not read this https://github.com/thomasloven/hass-browser_mod#installation-instructions, and got the same problem. Uninstall, restart and reinstall solved my issue.

**Comment by thomasloven** [comment] 2022-09-04 11:16
Duplicate of #359

**Closed by thomasloven** 2022-09-04 11:16 UTC
