### ISSUE TITLE
Custom element doesn't exist: hui-entity-filter-card

### ISSUE THREAD

**Issue by jarrah31** [thomasloven/hass-browser_mod#96] opened 2020-05-20 12:22 UTC
Since upgrading to 1.108.9 from 1.106, my popup cards have been giving the following error:

![image](https://user-images.githubusercontent.com/3072303/82445385-9d214380-9a9c-11ea-8669-8c007e19df73.png)

I thought this might be related to the new loading feature in 1.107, so I tried Lovelace Card Preloader but that hasn't helped either. 

Here is my code to reproduce the issue.

```
resources:
  - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
    type: js
 
preload_cards:
  - entity-filter

title: Home
views:
  - title: Test2
    panel: false
    path: test2
    popup_cards:
      input_boolean.window_is_open:
        title: Open Windows
        card:
          type: entity-filter
          state_filter:
            - "Open"
          entities:
            - sensor.win_lounge_top_left
            - sensor.win_lounge_top_right
    cards:
      - type: conditional
        conditions:
          - entity: input_boolean.kiosk_cond_btt1
            state: "on"
        card:
          type: button
          name: Turn Off Lights
          entity: input_boolean.window_is_open
          tap_action:
            action: more-info
```
Thanks.

**Comment by heymoe** [comment] 2020-05-23 14:33
I have a similar issue after upgrading to 0.110.1 and upgrading to the latest version of this integration (from 25 to 27) yesterday.

My map popup_card fails with:
`Custom element doesn't exist: hui-map-card.`

Here is my code:
```
popup_cards:
      device_tracker.xxx_position:
        card:
          aspect_ratio: 16x9
          default_zoom: 14
          entities:
            - device_tracker.xxx_position
          hours_to_show: 12
          title: null
          type: map
        style:
          width: 60%
        title: xxx
```

This worked fine when running 0.109.6 and version 25 of this integration.

**Comment by heymoe** [comment] 2020-05-25 15:38
While messing around with my HA dashboard this morning I noticed that my map popup was working again, sort of.  I thought that's odd so I clicked on the refresh button of my browser and after the refresh it stopped working again. After messing around some more I figured out a procedure to get it working again until you refresh the page again.

I'm using Windows 10 and Chrome to access my HA dashboard and I also tested this procedure with Firefox with the same results.

To start, I open a new tab in Chrome and go to my HA dashboard. At this point if I click on the element that should popup my map view, I get the error that I reported in my previous comment.

Next from this tab that is currently broken, I clicked on the configuration icon from the HA menu on the left hand side using my middle mouse  button (you can pretty much middle click on any of the menu icons though). Using the middle mouse button opens the HA configuration screen in a new tab in Chrome. From this new tab, if I go back to my dashboard view, my map popups work.

If you got back to the original Chrome tab, it's still broken and if you refresh the new tab that is working, it stops working upon refresh. 

You have to open this new tab via a middle click. You can't just open a new tab empty tab and go to your HA URL.

Another thing I've noticed is that I have another popup that doesn't load a map but a "custom:roku-card" and that popup works fine.

Very strange.  The only thing that has changed since my previous comment was I upgraded to HA 0.110.2 and HACS to 1.03 from 1.01. I'm not sure if this middle click trick worked or did not work prior to those updates.

**Comment by alexbelgium** [comment] 2020-07-07 21:48
Same issue with picture card : Custom element doesn't exist: hui-picture-card. Just after setting it, it works then after a couple minutes I've got this message instead.

**Comment by jarrah31** [comment] 2020-07-09 08:55
I'm on HA 111.2 and release 26 of Browser Mod and no longer have this issue, so happy to close if needs be.

**Comment by heymoe** [comment] 2020-07-09 15:45
I'm running HA 112.4 and release 29 of Browser Mod (Installed via HACS) and I still have the same issue.

**Comment by jarrah31** [comment] 2020-07-10 15:00
Oops, I meant release 29.

Not sure if it helps, but I've put my ui-lovelace resources: section in configuration.yaml due to the changes made in 107. Do you still have yours in ui-lovelace.yaml?

**Comment by heymoe** [comment] 2020-07-10 15:40
I no longer have an active ui-lovelace.yaml file (it's been renamed to .old) and my configuration.yaml does not have a "resource:" section anymore since HA has moved that management to the UI under: Configuration -> Lovelace Dashboards -> Resources which HACS modifies as needed for the addons installed under it.

**Comment by Shamshala** [comment] 2020-07-21 16:40
I'm not sure if it's related but i have basically the same issue. I see this issue often via Mobile App but sometimes even via desktop. The interesting part is, despite there is the right path for browser_mod.js in recources, every `Custom element...` error seems to be caused by trying to access `/config/www/community/browser_mod/browser_mod.js`. (never been there, installed via HACS)

**Comment by KTibow** [comment] 2020-08-31 21:27
Duplicate of #92

**Closed** 2020-10-21 18:43 UTC
